apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shipment-binding
  namespace: default
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: gatewayAddr
      value: localhost:26500
    - name: gatewayKeepAlive
      value: 45s
    - name: usePlainTextConnection
      value: true
    - name: workerName
      value: calculator
    - name: workerTimeout
      value: 30s
    - name: requestTimeout
      value: 15s
    - name: jobType
      value: shipment-binding
    - name: maxJobsActive
      value: 32
    - name: concurrency
      value: 4
    - name: pollInterval
      value: 100ms
    - name: pollThreshold
      value: 0.3
    - name: fetchVariables
      value: operator, firstOperand, secondOperand
